### ISSUE TITLE
Usability with mcp23017 pins

### ISSUE THREAD

**Issue by tokazio** [Testato/SoftwareWire#23]
Can we make it usable with some mcp23017 ports ?

**Comment by Koepel** [comment]
Do you want to use SoftwareWire for a MCP23017 or do you want to create another I2C bus with the I/O pins of the MCP23017 ?

A fall-back with normal pinMode() and digitalRead(), digitalWrite() functions has still to be added. After that those could be replaced with similar functions of a MPC23017 library. That will be a very slow I2C bus.
What would be the advantage, since there is already a I2C bus (between the Arduino and the MCP23017).

**Comment by Testato** [comment]
Closed for inactivities
